<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Approved Leave Requests - {{ $month }} {{ $year }}</title>
    <style>
        @page {
            size: legal landscape;
            margin: 0.5in;
        }

        body {
            margin: 0;
            padding: 0;
            font-size: 12px;
            font-family: Arial, sans-serif;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #333;
        }

        .header h1 {
            font-size: 18px;
            font-weight: bold;
            margin: 5px 0;
            color: #333;
        }

        .header h2 {
            font-size: 16px;
            font-weight: normal;
            margin: 5px 0;
            color: #666;
        }

        .header h3 {
            font-size: 20px;
            font-weight: bold;
            margin: 10px 0;
            color: #1865a6;
        }

        .info-section {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            font-size: 11px;
        }

        .info-left, .info-right {
            width: 48%;
        }

        .table-container {
            margin-top: 20px;
        }

        .requests-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 10px;
            margin-top: 10px;
        }

        .requests-table th,
        .requests-table td {
            border: 0.5px solid #333;
            padding: 8px 4px;
            text-align: center;
            vertical-align: middle;
        }

        .requests-table th {
            background-color: #f0f0f0;
            font-weight: bold;
            font-size: 9px;
        }

        .requests-table td {
            font-size: 9px;
        }

        .requests-table .text-left {
            text-align: left;
        }

        .role-badge {
            padding: 2px 6px;
            border-radius: 10px;
            font-size: 8px;
            font-weight: bold;
            color: white;
        }

        .role-school-head {
            background-color: #8B5CF6;
        }

        .role-teacher {
            background-color: #3B82F6;
        }

        .role-other {
            background-color: #6B7280;
        }

        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ccc;
            display: flex;
            justify-content: space-between;
            font-size: 11px;
        }

        .footer-left {
            width: 60%;
        }

        .footer-right {
            width: 35%;
            text-align: right;
        }

        .signature-section {
            margin-top: 40px;
            display: flex;
            justify-content: space-between;
        }

        .signature-box {
            width: 30%;
            text-align: center;
        }

        .signature-line {
            border-bottom: 1px solid #333;
            margin-bottom: 5px;
            height: 40px;
        }

        .total-summary {
            background-color: #f8f9fa;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
            text-align: center;
            font-weight: bold;
        }
    </style>
</head>

<body>
    <!-- Header Section -->
    <div class="header">
        <h1>Republic of the Philippines</h1>
        <h1>Department of Education</h1>
        <h2>Region VIII - Eastern Visayas</h2>
        <h2>SCHOOLS DIVISION OF BAYBAY CITY</h2>
        <h2>Brgy. Gaas, Baybay City, Leyte</h2>
        <h3>APPROVED LEAVE REQUESTS REPORT</h3>
    </div>

    <!-- Report Information -->
    <div class="info-section">
        <div class="info-left">
            <strong>Report Period:</strong> {{ $month }} {{ $year }}<br>
            <strong>Total Approved Requests:</strong> {{ $totalRequests }}<br>
            <strong>Report Type:</strong> Approved Leave Requests
        </div>
        <div class="info-right">
            <strong>Generated On:</strong> {{ $generatedAt }}<br>
            <strong>Generated By:</strong> System Administrator<br>
            <strong>Status:</strong> Official Report
        </div>
    </div>

    <!-- Summary Section -->
    <div class="total-summary">
        Total Approved Leave Requests: {{ $totalRequests }} requests for {{ $month }} {{ $year }}
    </div>

    <!-- Requests Table -->
    <div class="table-container">
        @if($requests->count() > 0)
        <table class="requests-table">
            <thead>
                <tr>
                    <th style="width: 5%;">#</th>
                    <th style="width: 20%;">Personnel Name</th>
                    <th style="width: 10%;">Role</th>
                    <th style="width: 20%;">School</th>
                    <th style="width: 15%;">Leave Type</th>
                    <th style="width: 15%;">Leave Period</th>
                    <th style="width: 8%;">Days</th>
                    <th style="width: 12%;">Approved Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($requests as $index => $request)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td class="text-left">
                        @if($request->user->personnel)
                            {{ $request->user->personnel->first_name }} {{ $request->user->personnel->last_name }}
                            @if($request->user->personnel->position)
                                <br><small style="color: #666;">{{ $request->user->personnel->position->title }}</small>
                            @endif
                        @else
                            {{ $request->user->name }}
                        @endif
                    </td>
                    <td>
                        <span class="role-badge 
                            @if($request->user->role === 'school_head') role-school-head
                            @elseif($request->user->role === 'teacher') role-teacher
                            @else role-other @endif">
                            {{ ucfirst(str_replace('_', ' ', $request->user->role)) }}
                        </span>
                    </td>
                    <td class="text-left">
                        @if($request->user->personnel && $request->user->personnel->school)
                            {{ $request->user->personnel->school->school_name }}
                            <br><small style="color: #666;">{{ $request->user->personnel->school->school_id }}</small>
                        @else
                            N/A
                        @endif
                    </td>
                    <td>{{ $request->leave_type }}</td>
                    <td>
                        {{ \Carbon\Carbon::parse($request->start_date)->format('M d, Y') }}
                        <br>to {{ \Carbon\Carbon::parse($request->end_date)->format('M d, Y') }}
                    </td>
                    <td>
                        {{ \Carbon\Carbon::parse($request->start_date)->diffInDays(\Carbon\Carbon::parse($request->end_date)) + 1 }}
                    </td>
                    <td>
                        {{ $request->updated_at->format('M d, Y') }}
                        <br><small>{{ $request->updated_at->format('g:i A') }}</small>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <div style="text-align: center; padding: 40px; color: #666;">
            <h3>No Approved Leave Requests Found</h3>
            <p>No leave requests were approved during {{ $month }} {{ $year }}</p>
        </div>
        @endif
    </div>

    <!-- Footer Section -->
    <div class="footer">
        <div class="footer-left">
            <strong>Note:</strong> This report contains all leave requests that were approved during the specified period.
            All data has been verified for accuracy and completeness.
        </div>
        <div class="footer-right">
            <strong>Page 1 of 1</strong><br>
            Generated by PIMS v1.0
        </div>
    </div>

    <!-- Signature Section -->
    <div class="signature-section">
        <div class="signature-box">
            <div class="signature-line"></div>
            <strong>Prepared by:</strong><br>
            System Administrator<br>
            {{ $generatedAt }}
        </div>
        <div class="signature-box">
            <div class="signature-line"></div>
            <strong>Reviewed by:</strong><br>
            Administrative Officer VI (HRMO II)<br>
            Date: ________________
        </div>
        <div class="signature-box">
            <div class="signature-line"></div>
            <strong>Approved by:</strong><br>
            Schools Division Superintendent<br>
            Date: ________________
        </div>
    </div>
</body>

</html>
