#!/bin/bash
# Run this script to complete the CTO time segments implementation

echo "CTO Time Segments Implementation Script"
echo "======================================="

echo ""
echo "Step 1: Running database migration..."
cd /d "e:\Projects\personal-info-management-system"
php artisan migrate --force

echo ""
echo "Step 2: Migration completed!"
echo ""
echo "Changes made to CTO Request system:"
echo "1. Updated database schema to include:"
echo "   - morning_in, morning_out"
echo "   - afternoon_in, afternoon_out"
echo "   - total_hours"
echo ""
echo "2. Updated CTORequest model to handle new fields"
echo ""
echo "3. Updated CTORequestController to:"
echo "   - Validate time segments like ServiceCreditRequest"
echo "   - Calculate total hours from time segments"
echo "   - Support both morning and afternoon work periods"
echo ""
echo "4. Updated CTO forms in:"
echo "   - school_head/partials/leaves.blade.php"
echo "   - non_teaching/partials/leaves.blade.php"
echo ""
echo "5. Updated JavaScript to calculate hours from time segments"
echo ""
echo "6. Updated admin CTO requests view to show time segments"
echo ""
echo "The system now works like the Service Credit system with:"
echo "- Morning Time In/Out"
echo "- Afternoon Time In/Out"
echo "- At least one complete pair required"
echo "- Automatic hour calculation"
echo ""
echo "Test the changes by:"
echo "1. Go to school head or non-teaching dashboard"
echo "2. Click 'Request CTO'"
echo "3. Enter morning and/or afternoon times"
echo "4. Verify hours are calculated automatically"
echo "5. Submit the request"
echo "6. Check admin panel to see time segments display"

pause
